url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "SignalWire Guides" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-gist